title: File

accept:
  type: image

tabs:
  content:
    label:
      en: Content
      es: Contenido
    fields:
      alt:
        label:
          en: Alt text
          es: Texto alternativo
        type: text
        help:
          en: Describe the image for accessibility and SEO.
          es: Describe la imagen para accesibilidad y SEO.
      caption:
        label:
          en: Caption
          es: Pie de foto
        type: writer
